only:
- master

before_install:
- npm install -g hexo    

install:
- npm install

before_script:
- git config --global user.name 'Tamirespaquino'
- git config --global user.email 'tamirespaquino@gmail.com'

script:
- hexo generate

after_success:
- mkidr .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m master
- git push -q -u origin master